language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.0
    - android-27
    - extra-android-m2repository
    
script:
      - ./gradlew build connectedCheck #edit your script here

notifications:
    on_success: change
    on_failure: change
