language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.0
    - android-25
    - android-25
    - extra-android-m2repository

script:
      - ./gradlew checkstyle build connectedCheck #edit your script here

notifications:
    on_success: change
    on_failure: never
