 language: android
 java: oraclejdk8 # We need this if your sdk version is 24
 android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-25.0.2
    - android-25

    # Support library
    - extra-android-support
    - extra-android-m2repository
    
    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-17
    
sudo: required

before_install:
 - chmod +x gradlew
 - chmod +x gradle/wrapper/gradle-wrapper.jar

script:
  - ./gradlew assembleRelease --stacktrace
